### ISSUE TITLE
The Doom2 broke 100% chance.

### ISSUE THREAD

**Issue by yu8349** [MadDeCoDeR/Classic-RBDOOM-3-BFG#146] opened 2024-04-02 12:36 UTC
When I played Doom2, now I'm in the map 13, before that, the game sometimes will be broken when I load the save file. But now I'm in the map 13, the game is broken everytime I load. It make me crazy. I use the 1.3.1 edtion. I saw you release the 1.3.2 edtion. But when I replace the file with it, the game sometimes can't start(break), sometimes I could enter the game, but I can't use the old save file. How could I fix it?

**Comment by yu8349** [comment] 2024-04-02 16:17
Edit: I got the log file. But I don't know how to find what is wrong. If you need it, I could send it.

**Comment by yu8349** [comment] 2024-04-04 04:54
> Just reuploaded 1.3.2. Now the issue should be resolved

Still can't load the 1.3.1 savefile, but I saw your patch changed the savefile's length. So it might lead to this result. Later today, I will open a new game and try to see if it will crash when playing later levels.

**Comment by yu8349** [comment] 2024-04-04 15:16
The problem of game can't open still here, but I missed to open OBS, so the video I can't send you now. The problem is the game will crash after open, my solution is that overwrite all 1.3.2 file even it's all 1.3.2 file. Then the problem is gone. I didn't do anything but after a few hours, the problem arises. So I think tomorrow I could send you a video.

**Comment by MadDeCoDeR** [comment] 2024-04-04 17:39
Hi, did it happened after you boot again the game?

**Comment by yu8349** [comment] 2024-04-04 18:26
> Hi, did it happened after you boot again the game?

It's late in my time. So I just could not give you a video. And your question just give me new ideas, so I just tried two situations.
1. Restart windows11, and change my windows lang to english, then open the game. The game could open normally.
2. Close the system then start the system.( I remember there is a difference between restarting and shutting down then starting), but I don't change the system lang (I use Chinese and a Chinese input software (not windows input). ), then the problem appear.
I have two conjectures.
1. It's clear that the BFA is not block input software, in 1.3.1 the game could open and then I change the system lang or just change the software to english mode. But in 1.3.2 it might lead to game crashed result.
2. It might because the game file has problem make some important game process couldn't load so I can't open the game and the reason why when I restart the system I could open the game, is restart windows11 is not shut down all process, before I restart I have opened the game normally, so the process is still there, then I could open the game.
Due to the others is not raised the issue of game not starting. So I think the first have bigger chance. I saw you use much C++ in the BFA edition so it is easy to block the input software.
Tomorrow I will try the others situation like start the system, and before I start the game, change my lang to english. And I will record my screen. Or when I get up, you might find the problem. LOL.

**Comment by yu8349** [comment] 2024-04-04 18:27
> > Hi, did it happened after you boot again the game?
> 
> It's late in my time. So sorry I could not give you a video. And your question just give me new ideas, so I just tried two situations.
> 
> 1. Restart windows11, and change my windows lang to english, then open the game. The game could open normally.
> 2. Close the system then start the system.( I remember there is a difference between restarting and shutting down then starting), but I don't change the system lang (I use Chinese and a Chinese input software (not windows input). ), then the problem appear.
>    I have two conjectures.
> 3. It's clear that the BFA is not block input software, in 1.3.1 the game could open and then I change the system lang or just change the software to english mode. But in 1.3.2 it might lead to game crashed result.
> 4. It might because the game file has problem make some important game process couldn't load so I can't open the game and the reason why when I restart the system I could open the game, is restart windows11 is not shut down all process, before I restart I have opened the game normally, so the process is still there, then I could open the game.
>    Due to the others is not raised the issue of game not starting. So I think the first have bigger chance. I saw you use much C++ in the BFA edition so it is easy to block the input software.
>    Tomorrow I will try the others situation like start the system, and before I start the game, change my lang to english. And I will record my screen. Or when I get up, you might find the problem. LOL.
Edit these words use me almost twenty mins. Cry face.

**Comment by yu8349** [comment] 2024-04-05 06:56
[https://drive.google.com/file/d/1qGKATEahMMzSId8NTAkX_us2sxzocp2N/view?usp=drive_link](url)
[https://drive.google.com/file/d/1g9vs-AnlrG8FlJEmSh-FmTe4H9e7r0CX/view?usp=drive_link](url)
I was wrong. And I was able to fix it according to yesterday's method, but today I was able to fix it the first time, but not the second time. I don't know why. Of course now I've fixed it again, but I don't understand at all why the game can run normally. I just After using 1.3.1 to start the game, I overwrote it with the 1.3.2 file, and then 1.3.2 can run.

**Comment by yu8349** [comment] 2024-04-05 06:59
By the way, I open the log file. It's all same except when the game crashed. The log stoped in here.
gamename: baseDOOM-1
gamedate: Apr  3 2024
Initializing event system
...535 event definitions
Initializing class hierarchy
...160 classes, 500760 bytes for event callbacks
Initializing scripts
Compiled 'D:\SteamLibrary\steamapps\common\DOOM 3 BFG Edition\base\script\doom_main.script': 4.1 ms
---------- Compile stats ----------

Memory usage:
     Strings: 120, 16800 bytes
  Statements: 95386, 3815440 bytes
   Functions: 3070, 521288 bytes
   Variables: 239712 bytes
    Mem used: 6352856 bytes
 Static data: 6295200 bytes
   Allocated: 8664336 bytes
 Thread size: 14072 bytes

...6 aas types
game initialized.
--------------------------------------
Warning when retrieving Display Modes: Code 3: The system cannot find the path specified.
Warning when retrieving Display Modes: Code 5: Access is denied.


normally, it will send out more.

**Comment by yu8349** [comment] 2024-04-05 07:04
> Hi, did it happened after you boot again the game?

the problem happened after I shut down and start the system.

**Comment by MadDeCoDeR** [comment] 2024-04-05 17:22
So I made the main menu creation logging a little bit more verbose. You can try to built it on your own and check it's log files to make sure that all the menus are created.
This is how it must look:

Creating Main Menu
Initializing Press Start
Initializing Root Menu
Initializing Single Player
Initializing Settings Menu
Initializing Load Game
Initializing New Game
Initializing Advanced Options
Initializing ASdvanced Graphics Options
Initializing System Options
Warning when retrieving Display Modes: Code 5: Access is denied.
Warning when retrieving Display Modes: Code 5: Access is denied.
Initializing Game Options
Initializing Party Lobby
Initializing Game Lobby
Initializing 3D Menu
Initializing Difficulty
Initializing Controls Options
Initializing Bindings
Initializing Resolution Menu
Initializing Controller Layout
Initializing DEV
Initializing Leaderboards
Initializing Gamepad
Initializing Advanced Controls Options
Initializing Match Settings
Initializing Mode Select
Initializing Browser
Initializing Credits


The reason why I did that is because from the log you show, it seems that it crashes when creating one of the menus

**Comment by yu8349** [comment] 2024-04-06 06:13
I should send you these two file.
[qconsole - 副本.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/14892653/qconsole.-.log)
[qconsole.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/14892654/qconsole.log)
But I think it's useless. Because it's all same thing.
If there is anything to analyse, it can only be something wrong in Loaded FFMPEG file: 'video/intro/introloop.bik',

**Comment by MadDeCoDeR** [comment] 2024-04-10 21:12
Great news. I manage to fix the nightly builds and also I have disabled a useless piece of code that might have caused the issue.
When you want download the latest nighlty build and check if it is any better.

**Comment by yu8349** [comment] 2024-04-11 03:08
> Great news. I manage to fix the nightly builds and also I have disabled a useless piece of code that might have caused the issue. When you want download the latest nighlty build and check if it is any better.

Oh, yeah. You completely fixed the issue of not booting, thank you and congratulations to you also to me, lol. I saw that you add the DEV could make us choose the level, it's a good function. Later, I will start to play DOOM 2 again. If anything is ok, I will close this issue.

**Comment by yu8349** [comment] 2024-04-12 03:35
I just triggered a crash, when I die, I load the game maybe too soon, so the game is crashed. I tried to recurrent this crash, but I failed, so I think it may not BFA promblem, it's DOOM2 with WIN 11 promblem. For now, the rest is okay. So I'm gonna close this issue. If the promblem appear again on the later level, I will open it.

**Comment by yu8349** [comment] 2024-04-12 09:07
[https://drive.google.com/file/d/1fTWQRLoxpY7UoB8Y5IfndE9UHQK9JGkC/view?usp=drive_link](url)
something is wrong, it seems some problem is here, but I'm not sure it's BFA problem or the origin game. so here is my save file. try load it see the problem could you get.
When I read this file, there is a spider when it hit you put F3 to load, then game will crash.
[https://drive.google.com/file/d/1b9lbZTPCKqhXZbjE4ma11WJ1cYdduGu3/view?usp=drive_link](url)

**Comment by yu8349** [comment] 2024-04-12 09:20
I may know what's wrong. There is a problem with the last save location. (I think, so you should check about this?) here is another file. it almost same. but with no crash.
[https://drive.google.com/file/d/16vch9xks4i9Lu1qIwKEK5kMqrzUtmNRN/view?usp=drive_link](url)

**Comment by yu8349** [comment] 2024-04-12 09:22
Later I will try to open a new game but keep using the last save location, let's see the crash will appear or not.

**Comment by yu8349** [comment] 2024-04-13 08:54
Ok, the sixth location started crashing in level four, I couldn't be sure if it will show up in level one to three because I'm so familiar with the levels, but I truly test many loading in level one to three, but didn't crash.
Now I'll try only to use one location except the sixth. (Yesterday I use both to save I mean one level one location, so the level one to five in location one to five will not crash, so don't need to test this situation more.)

**Comment by MadDeCoDeR** [comment] 2024-04-13 09:05
So the issue is with that specific save file?

**Comment by yu8349** [comment] 2024-04-13 09:17
> So the issue is with that specific save file?

yesterday file? yeah the first is video, second is problem file, third is good file.
It's bad that I used the second location in level four also crashed just now.

**Comment by yu8349** [comment] 2024-04-13 09:31
I just delete all file and start new game again. Level fou in location two crashed. I will test one more location to be sure the level problem or the level(game).

**Comment by yu8349** [comment] 2024-04-13 09:47
I just test location 1 and 3, all crash in level four, oh it may help that I save in same location in level, then load.

**Comment by MadDeCoDeR** [comment] 2024-04-17 19:29
The issue should be fixed now. Check the latest nightly build

**Comment by yu8349** [comment] 2024-04-19 10:35
> The issue should be fixed now. Check the latest nightly build

Really sorry, I saw this message 2 days later. I will try it later.

**Comment by MadDeCoDeR** [comment] 2024-04-19 16:27
> > The issue should be fixed now. Check the latest nightly build
> 
> Really sorry, I saw this message 2 days later. I will try it later.

No worries, when you want and can test it and either close the issue or tell me to close it

**Comment by yu8349** [comment] 2024-04-20 16:39
I just load the file(level four) and reload it. Glad it's not break the game now. It's a good start. I will play more tomorrow. My time is quite late. I think tomorrow I will past the level ten at least. And I will reload the file at least four times. I will reply when I finished.

**Comment by yu8349** [comment] 2024-04-21 11:51
OK. I just pasted level ten, I promise we have no problem in one to ten. So I guess it's done. You fixed it 100%. So I will update my steam post to tell them who will use the BFA edtion to use [DOOM BFA Nigthly 2024-04-17-19-26], so one more question and you could close this issue when you answer. Is the Nightly release could run alone? I mean if I'm a newer for this, should I download the 1.3.2 then overwrite with the Nightly release or I just download the Nightly release. And I should download [windows-RC-debug-x64.zip] right?

**Comment by MadDeCoDeR** [comment] 2024-04-21 13:37
> OK. I just pasted level ten, I promise we have no problem in one to ten. So I guess it's done. You fixed it 100%. So I will update my steam post to tell them who will use the BFA edtion to use [DOOM BFA Nigthly 2024-04-17-19-26], so one more question and you could close this issue when you answer. Is the Nightly release could run alone? I mean if I'm a newer for this, should I download the 1.3.2 then overwrite with the Nightly release or I just download the Nightly release. And I should download [windows-RC-debug-x64.zip] right?

Yes, nightly builds are standalone. The main release might have some additional tools (like a launcher and some modding tools) bundled in but you don't need them in order to just run DOOM BFA. The debug nightly builds as the name implies is for debugging purposes (in the case of end users (players) it is for better logging), even though it offers the elusive DEV menu it doesn't allow achievements to be unlocked. So if you want to unlock achievements better go for the retail ones instead (also the retail ones are taking less space)

**Closed** 2024-04-21 13:38 UTC

**Comment by yu8349** [comment] 2024-04-21 14:40
thank you for your explain. I have three doom 2 achievements need to be unlocked. I change to retail now, could I still use the debug save file to unlock achievements? Or I need a new one.
