### ISSUE TITLE
Viewmodel FoV is broken

### ISSUE THREAD

**Issue by Blitzoreo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#25] opened 2019-04-16 11:38 UTC
**Describe the bug**
The Viewmodel FoV option, either in the options menu or console command, doesn't work accordingly.

**To Reproduce**
Either go to Advanced Options and switch the Viewmodel FoV or use console command "pm_vmfov".

**Expected behavior**
It should change the position of your weapon, either further ahead of you or closer.
Instead, only the "light" on select weapons (Machinegun, Chaingun, Plasma) is moved around, not the model itself.

**Additional context**
I would make this another issue but I think it can go here just fine...
It seems that pressing on the Viewmodel FoV bar in Advanced Options crashes my game, no idea why. I can easily use arrow keys to switch it around though.

**Comment by MadDeCoDeR** [comment] 2019-04-30 12:52
So did I fixed it?

**Comment by Revenile** [comment] 2019-07-28 03:57
At FOV at 85, the view model distance does work, however I'm getting interesting issue involving the glow, so far only seen on the PDA and SMG.  The glow from their displays creates a 'box' of light that just ends.  The only fix I've found right now is turning the view distance back to the lowest setting.  The farther away the models are, the more visible the issue is.

![20190727203709_1](https://user-images.githubusercontent.com/36957440/62002015-e1c49400-b0b0-11e9-9045-1fe4bfdb7a1f.jpg)
![20190727203720_1](https://user-images.githubusercontent.com/36957440/62002016-e426ee00-b0b0-11e9-8f85-6fdbd8c4b8f4.jpg)

I just thought I'd bring this up just to insure you're aware of it, if there's no fix then that's fine, I don't mind having my guns against my cheek, but I do like the view models being farther away.

**Comment by MadDeCoDeR** [comment] 2019-07-28 05:54
I'm aware of this bug and sadly haven't found any solution yet.
I would advise through to lower the FOV if it really annoys you.

**Comment by Revenile** [comment] 2019-07-28 10:44
I figured that was the case, and it's ok, shame a fix hasn't been found yet, I do like the feature.

**Comment by RinMaru** [comment] 2019-09-18 04:01
This issue also breaks the Flashlight causing unusual cut off.

**Comment by MadDeCoDeR** [comment] 2020-08-24 21:14
The issue is now fixed with the commit d9626adc9beb385abcdc2685bbe14f440a636180. So this issue will close now.

**Closed by MadDeCoDeR** 2020-08-24 21:14 UTC
