### ISSUE TITLE
The Final Bug Report (I Hope)

### ISSUE THREAD

**Issue by Robin613507** [MadDeCoDeR/Classic-RBDOOM-3-BFG#44] opened 2020-02-29 18:27 UTC
This Might Be The Final Bug Report 

The Problem Is That Last Time It Always Crashes On Some Things Like When Going To The Elevator In Mars City Underground

Second Of All When Opening The Game It Shows It Opens But It Wont Let Me Play What Do I Have To Do

I Hope The Other Version 1.2.3.2 Fixed The Crash Problem But What Do I Have To Do To Play I Extracted The Source Code And Everything

**Comment by MadDeCoDeR** [comment] 2020-02-29 18:45
A. Launch the game with the parameter +set logfile 1 and send me the contents of the qconsole.log which should be on C:\Users\<username>\Saved Games\Id Software\DOOM BFA\base
B. Download the Binaries of version 1.2.3.2 from here https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/releases/tag/1.2.3.2-BFA and just extract it's content in the game's folder and just run the installer inside the msvc 2015-2019

**Comment by Robin613507** [comment] 2020-02-29 18:57
The Gane Wont Open Read The Full Report

**Comment by MadDeCoDeR** [comment] 2020-02-29 18:59
Even if it don't open the log file will record what happened before It try to open

**Comment by Robin613507** [comment] 2020-02-29 19:08
Then How Can I Enable It If I Cant Open It

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:15
right click the .bat file and select edit. Add " +set logfile 1" and save it. Open the .bat file

**Comment by Robin613507** [comment] 2020-02-29 19:16
With + Or Without

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:16
With +

**Comment by Robin613507** [comment] 2020-02-29 19:18
I Didnt Get The qconsole

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:19
Have you check the C:\Users\<username>\Saved Games\Id Software\DOOM BFA\base folder ?

**Comment by Robin613507** [comment] 2020-02-29 19:20
Yes I Didnt Even Got The DOOM BFA Inly RBDOOM3BFG Folder

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:21
A. What version are you using ?
B. Check the RBDOOM 3 BFG\base folder

**Comment by Robin613507** [comment] 2020-02-29 19:22
A The Latest New Version 
B I Only Got The Old qconsole Which Was Used For Crashing

**Comment by Robin613507** [comment] 2020-02-29 19:23
The Error Also Happend On Old Versions But Rarely

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:24
try +set r_fullscreen 0 (like +set logfile 1)

**Comment by Robin613507** [comment] 2020-02-29 19:29
Bad News: It Still Wont Open The Game 
Good News: It Shows That It Opens On Task Manager

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:31
How the .exe or .bat file is named ?

**Comment by Robin613507** [comment] 2020-02-29 19:33
DoomBFA

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:35
and there is NO DOOM BFA folder on C:\Users\<YOUR WINDOWS USERNAME>\Saved Games\id Software ?

**Comment by Robin613507** [comment] 2020-02-29 19:39
Nope Just The Old RBDOOM3BFG Folder

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:40
What are your System Specs ?

**Comment by Robin613507** [comment] 2020-02-29 19:44
Intel Pentium CPU B960 2.20 GHz

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:45
Memory ? GPU ? OS ?

**Comment by Robin613507** [comment] 2020-02-29 19:47
OS 32 Bit
GPU ? Its Something Like Intel
Memory ? Dont Know

**Comment by MadDeCoDeR** [comment] 2020-02-29 19:49
Since Version 1.2.0 there have been a huge change to the rendering code and is more demanding than before. You might have to upgrade your PC in order to play it.

**Comment by Robin613507** [comment] 2020-02-29 19:58
I Dont Think Thats The Reason Why I Canr Open It It Happend On Older Versions Too But Rarely It Showa That Its Open In The Task Manager

**Comment by MadDeCoDeR** [comment] 2020-02-29 20:16
Then it just fails to create that folder and that is why it crashing.
Run it as admin

**Comment by Robin613507** [comment] 2020-02-29 20:49
Still Wont Work Screw This I Will Never Get To Enjoy This Mod Its A Good Mod This Happend It Other Old Versions Too Maybe Its Because Of The Mod I Hope It Gets Fixed Like The 32 Bit Support

**Comment by Robin613507** [comment] 2020-02-29 21:06
Still I Wont Give Up Isnt There A Way To Fix this is a new update And that it could run in almost all pc's my pc can run my pc is like medium settings except of course its 32 bit

**Comment by MadDeCoDeR** [comment] 2020-02-29 21:16
As I said earlier the issue is that it doesn't create that folder. That usually might happen if your PC is blocking write access to the game on your user folder. Check your antivirus or just right click the .exe and select run as administrator

**Comment by Robin613507** [comment] 2020-03-01 08:45
Windows cannot find DOOMBFA.exe Make sure you typed the name correctly and then try again while the name is typed corectly

**Comment by MadDeCoDeR** [comment] 2020-03-01 10:13
Try DoomBFA.exe

**Comment by Robin613507** [comment] 2020-03-01 10:43
Wont Open Runned As Admin

**Comment by MadDeCoDeR** [comment] 2021-06-15 15:43
This didn't seem to went anywhere. Closing

**Closed by MadDeCoDeR** 2021-06-15 15:43 UTC
