### ISSUE TITLE
Use the cheat code will shutdown the achievements about Doom2?

### ISSUE THREAD

**Issue by yu8349** [MadDeCoDeR/Classic-RBDOOM-3-BFG#147] opened 2024-04-24 08:02 UTC
I added the launch option "-classich" to use "iddt" in doom2 after I tried to find the last monster for ten minutes(maybe more). Then I close the game and replace the save file which I backed up. My question is could I unlock the achievements if I just use it, and no save file change. I don't know if I will use it again. Finding the last monster for many minuts is depressing.

**Comment by MadDeCoDeR** [comment] 2024-04-24 08:05
Sadly that's not a bug that's a feature. I put this limitation on purpose in order to ensure that players won't cheat their way to unlock all the achievements.

**Comment by yu8349** [comment] 2024-04-24 08:38
Ok, is my step avoid the lock? I mean I delete the cheat file and use another not cheat one.

**Comment by MadDeCoDeR** [comment] 2024-04-24 16:31
Yeah, I will have to patch it (which also will mean that it will break save files again)

**Comment by MadDeCoDeR** [comment] 2024-04-24 16:49
I just pushed the fix and the nightly builds are getting build. If you don't want to lose your progress don't use it. Otherwise you will have to start a new game, since the update breaks all the old save files for Classic DOOM

**Comment by yu8349** [comment] 2024-04-25 02:09
> I just pushed the fix and the nightly builds are getting build. If you don't want to lose your progress don't use it. Otherwise you will have to start a new game, since the update breaks all the old save files for Classic DOOM

OK, I don't want to use it because it only update anti cheat not a bug fix. I think I could restrain myself from using cheat codes.

**Closed** 2024-05-15 16:04 UTC
