### ISSUE TITLE
all stereoscopic 3D modes are broken

### ISSUE THREAD

**Issue by TheVoodoo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#8] opened 2018-09-30 17:38 UTC
Stereoscopic 3D Modes are broken.

![screen_sbs](https://user-images.githubusercontent.com/16653359/46260397-9750a600-c4e5-11e8-830f-918e0cc2e34f.jpg)
![screen_tb](https://user-images.githubusercontent.com/16653359/46260398-9750a600-c4e5-11e8-9f76-990d8a483842.jpg)

Codes4Fun managed to fix it, few years ago...
https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/e83aa52d4f1ba778f90ebea986169b0559a4e731

There are also some other great changes he made on Oct 25, 2016.
https://github.com/RobertBeckebans/RBDOOM-3-BFG/commits/master?after=57041299eefe901555113810be89250d467034db+34

Would love to see it implemented in this project.

**Comment by MadDeCoDeR** [comment] 2018-09-30 17:49
That is weird I forked RBDoom 3BFG end of march 2017, also I tested the 3d modes and all seem to work fine

**Comment by MadDeCoDeR** [comment] 2018-09-30 18:36
Ok, apparently these fixes have been added After I fork the original RBDoom.
So as you suggested I put (at least the ones that might mater) on my version too.
I'm not gonna make prebuild binaries if you want these changes download the code and compile it

**Comment by MadDeCoDeR** [comment] 2018-10-02 11:13
The issue is fixed on version 1.1.11-classic.h4

**Closed by MadDeCoDeR** 2018-10-02 11:13 UTC
Labels: bug
